[theme]
primaryColor = "#006699"         # calm professional blue for buttons and highlights
backgroundColor = "#ffffff"      # white background for clean, bright look
secondaryBackgroundColor = "#f5f5f5"  # light gray for sidebars and containers
textColor = "#1c1c1c"            # soft black for legibility
font = "sans serif"              # clean default font family

[server]
headless = true
enableCORS = false
port = 8501
